extends:
  - spectral:oas

rules:
  operation-2xx-response: off
  operation-success-response: off
  info-license: off
  no-eval-template-literals: warn
  no-script-tags-in-description: warn
  openapi-tags-alphabetical: off
  no-undefined-server: off
  oas3-unused-components-schemas: off
  oas3-unused-components-responses: off
